{
  west: {
    kitchen: ['À LA CARTE MENU', 'ROSE BRUNCH','COCKTAILS','DESSERTS','VALENTINE’S SIGNATURE','VALENTINE’S PREMIUM'],
image:'https://www.pexels.com/photo/1640777/download/',
restaurantDescription:'Enjoy views of West London alongside sophisticated and classic dishes from our rotisserie and grill; all cooked in our open kitchen.',
    menuName: [[ {
      menuTitle: 'snacks',
    },
    { menuCol: 'seasonal crudités (v)', menuNum: '12' },
    { menuCol: 'seared smoked salmon', menuNum: '123' },
    { menuCol: 'iberico bsdellota ham (50g)', menuNum: '123' },
    {
      menuTitle: 'raw bar',
    },
    { menuCol: 'marinated tuna slices avocado, garlic & chilli', menuNum: '12' },
    { menuCol: 'beef carpaccio asdmustard dressing, parmesan & herbs', menuNum: '123' },
    { menuCol: 'steak tasdasartare aged cheddar & beef tomato', menuNum: '123' },
    { menuCol: 'diver scallops trsduffle & artichoke', menuNum: '123' },
    {
      menuTitle: 'starters',
    },
    { menuCol: 'crispy squid chilli & lime', menuNum: '12' },
    { menuCol: 'truffle flatbread pancetta & ricotta', menuNum: '123' },
    { menuCol: 'crab cake watercress, wasabi mayo', menuNum: '123' },
    { menuCol: 'smoked salmon flatbread imperial caviar & cream cheese', menuNum: '123' },
 ],
 [ {
  menuTitle: 'snacks',
},
{ menuCol: 'seasonal crudités (v)', menuNum: '12' },
{ menuCol: 'seared smoked salmon', menuNum: '123' },
{ menuCol: 'iberico belloasdta ham (50g)', menuNum: '123' },
{
  menuTitle: 'raw bar',
},
{ menuCol: 'marinated tuna slices avocado, garlic & chilli', menuNum: '12' },
{ menuCol: 'beef carpacasdascio mustard dressing, parmesan & herbs', menuNum: '123' },
{ menuCol: 'steak tartare aged cheddar & beef tomato', menuNum: '123' },
{ menuCol: 'diver scallops truffasdasle & artichoke', menuNum: '123' },
{
  menuTitle: 'starters',
},
{ menuCol: 'criddddspy squid chilli & lime', menuNum: '12' },
{ menuCol: 'truffle flatbread paasdancetta & ricotta', menuNum: '123' },
{ menuCol: 'crab cake watercress, wasabi mayo', menuNum: '123' },
{ menuCol: 'smoked salmon flatasdabread imperial caviar & cream cheese', menuNum: '123' },
],
[ {
  menuTitle: 'COCKTAILS',
},
{ menuCol: 'oblix tonix tanqueray 10 gin, lemon bitters, oblix tonix', menuNum: '12' },
{ menuCol: 'rubus sparkler tanqueray london dry gin raspberry, lavender, lime, sparkling wine', menuNum: '123' },
{ menuCol: 'blueberry martini ketel one vodka, blueberry, violet, lemon, egg whites', menuNum: '123' },
{ menuCol: 'ginger peach mule bulleit bourbon, ginger peach cordial, lime, ginger beer', menuNum: '123' },
{ menuCol: 'watermelon spritzer aperol, wat34ermelon, lemon, sparkling wine', menuNum: '123' },   { menuCol: 'ginger peachsdfsdf mule bulleit bourbon, ginger peach cordial, lime, ginger beer', menuNum: '123' },
{ menuCol: 'watermelon spritzer aperol, watermelon, lemon, sparkling wine', menuNum: '123' },   { menuCol: 'ginger peach mule bulleit bourbon, ginger peach cordial, lime, ginger beer', menuNum: '123' },
{ menuCol: 'watermelon s345rtpritzer aperol, watermelon, lemon, sparkling wine', menuNum: '123' },   { menuCol: 'ginger peach mule bulleit bourbon, ginger peach cordial, lime, ginger beer', menuNum: '123' },
{ menuCol: 'watermelon spritzer aperol, watsdsdfermelon, lemon, sparkling wine', menuNum: '123' },   { menuCol: 'ginger peach mule bulleit bourbon, ginger peach cordial, lime, ginger beer', menuNum: '123' },
{ menuCol: 'watermelon spritzer aperol, watermelon, lemon, sparkling wine', menuNum: '123' },   { menuCol: 'ginger peach msdfule bulleit bourbon, ginger peach cordial, lime, ginger beer', menuNum: '123' },
{ menuCol: 'watermelon spritzer aperol, watermelon, lemon, sparkling wine', menuNum: '123' },   { menuCol: 'ginger peach mule bulleit bourbon, ginger peach cordial, lime, ginger beer', menuNum: '123' },
{ menuCol: 'watermelon spridrtdrtzer aperol, watermelon, lemon, sparkling wine', menuNum: '123' },
{
  menuTitle: 'beers',
},
{ menuCol: 'NOAM BAVARIAN LAGER (340ml)', menuNum: '12' },
{ menuCol: 'ST MUNGO LAGER (330ml)', menuNum: '123' },
{ menuCol: 'SASSY L’INIMITABLE APPLE', menuNum: '123' },
{ menuCol: 'CIDER (330ml)', menuNum: '123' },
{ menuCol: 'LUCKY SAINT ALCOHOL FREE (330ml)', menuNum: '123' }],
    ],
  },
  east: {
    kitchen: ['BAR MENU', 'AFTERNOON TEA','OBLIX EASY','VALENTINES MENU'],
    image:'https://foodfriends-green.ru/wp-content/uploads/2021/02/photo-1547592180-85f173990554.jpg',
    restaurantDescription:'Enjoy views of East London, culinary cocktails and innovative seasonal dishes in a creative and relaxing dining and bar space.',
    menuName: [[ {
      menuTitle: 'COCKTAILS',
    },
    { menuCol: 'oblix tonix tanqueray 10 gin, lemon bitters, oblix tonix', menuNum: '12' },
    { menuCol: 'rubus sparkler tanqueray london dry gin raspberry, lavender, lime, sparkling wine', menuNum: '123' },
    { menuCol: 'blueberry martini ketel one vodka, blueberry, violet, lemon, egg whites', menuNum: '123' },
    { menuCol: 'ginger peach mule bulleit bourbon, ginger peach cordial, lime, ginger beer', menuNum: '123' },
    { menuCol: 'watermelon spritzer aperol, wat34ermelon, lemon, sparkling wine', menuNum: '123' },   { menuCol: 'ginger peachsdfsdf mule bulleit bourbon, ginger peach cordial, lime, ginger beer', menuNum: '123' },
    { menuCol: 'watermelon spritzer aperol, watermelon, lemon, sparkling wine', menuNum: '123' },   { menuCol: 'ginger peach mule bulleit bourbon, ginger peach cordial, lime, ginger beer', menuNum: '123' },
    { menuCol: 'watermelon s345rtpritzer aperol, watermelon, lemon, sparkling wine', menuNum: '123' },   { menuCol: 'ginger peach mule bulleit bourbon, ginger peach cordial, lime, ginger beer', menuNum: '123' },
    { menuCol: 'watermelon spritzer aperol, watsdsdfermelon, lemon, sparkling wine', menuNum: '123' },   { menuCol: 'ginger peach mule bulleit bourbon, ginger peach cordial, lime, ginger beer', menuNum: '123' },
    { menuCol: 'watermelon spritzer aperol, watermelon, lemon, sparkling wine', menuNum: '123' },   { menuCol: 'ginger peach msdfule bulleit bourbon, ginger peach cordial, lime, ginger beer', menuNum: '123' },
    { menuCol: 'watermelon spritzer aperol, watermelon, lemon, sparkling wine', menuNum: '123' },   { menuCol: 'ginger peach mule bulleit bourbon, ginger peach cordial, lime, ginger beer', menuNum: '123' },
    { menuCol: 'watermelon spridrtdrtzer aperol, watermelon, lemon, sparkling wine', menuNum: '123' },
    {
      menuTitle: 'beers',
    },
    { menuCol: 'NOAM BAVARIAN LAGER (340ml)', menuNum: '12' },
    { menuCol: 'ST MUNGO LAGER (330ml)', menuNum: '123' },
    { menuCol: 'SASSY L’INIMITABLE APPLE', menuNum: '123' },
    { menuCol: 'CIDER (330ml)', menuNum: '123' },
    { menuCol: 'LUCKY SAINT ALCOHOL FREE (330ml)', menuNum: '123' }],[ {
      menuTitle: 'COCKTAILS',
    },
    { menuCol: 'oblix tonix tanqueray 10 gin, lemon bitters, oblix tonix', menuNum: '12' },
    { menuCol: 'rubus sparkler tanqueray london dry gin raspberry, lavender, lime, sparkling wine', menuNum: '123' },
    { menuCol: 'blueberry martini ketel one vodka, blueberry534, violet, lemon, egg whites', menuNum: '123' },
    { menuCol: 'ginger peach mule bulleit bourbon, ginger peach cordial, lime, ginger beer', menuNum: '123' },
    { menuCol: 'watermelon spritzer aperol, watermelon, lemon, sparkling wine', menuNum: '123' },   { menuCol: 'ginger peach mule bulleit bourbon, ginger peach cordial, lime, ginger beer', menuNum: '123' },
    { menuCol: 'watermelon spritzer aperol, watermelon, lemon, sparkling wine', menuNum: '123' },   { menuCol: 'ginger peach mule bulleit bourbon, ginger peach cordial, lime, ginger beer', menuNum: '123' },
    { menuCol: 'watermelon spritzer aperol,34534 watermelon, lemon, sparkling wine', menuNum: '123' },   { menuCol: 'ginger peach mule bulleit bourbon, ginger peach cordial, lime, ginger beer', menuNum: '123' },
    { menuCol: 'watermelon spritzer aperol, watermelon, lemon, sparkling wine', menuNum: '123' },   { menuCol: 'ginger peachtery mule bulleit bourbon, ginger peach cordial, lime, ginger beer', menuNum: '123' },
    { menuCol: 'watermelon spritzer aperol, watermelon, lemon, sparkling wine', menuNum: '123' },   { menuCol: 'ginger peach mule bulleit bourbon, ginger peach cordial, lime, ginger beer', menuNum: '123' },
    { menuCol: 'watermelon spritzerertert aperol, watermelon, lemon, sparkling wine', menuNum: '123' },   { menuCol: 'ginger peach mfghule bulleit bourbon, ginger peach cordial, lime, ginger beer', menuNum: '123' },
    { menuCol: 'watermelon spritzer aperol, watermelon, lemon, sparkling wine', menuNum: '123' },
    {
      menuTitle: 'beers',
    },
    { menuCol: 'NOAM BAVARIAN LAGER (340ml)', menuNum: '12' },
    { menuCol: 'ST MUNGO LAGER (330ml)', menuNum: '123' },
    { menuCol: 'SASSY L’INIMITABLE APPLE', menuNum: '123' },
    { menuCol: 'CIDER (330ml)', menuNum: '123' },
    { menuCol: 'LUCKY SAINT ALCOHOL FREE (330ml)', menuNum: '123' }],

   
  ],
  }, 
  bar: {
    kitchen: ['bar' ],
    image:'https://cdn.pixabay.com/photo/2020/01/24/09/23/bar-4789760_1280.jpg',
    restaurantDescription:'Enjoy views of East London, culinary cocktails and innovative seasonal dishes in a creative and relaxing dining and bar space.',

    menuName: [[ {
      menuTitle: 'COCKTAILS',
    },
    { menuCol: 'oblix tonix tanqueray 10 gin, lemon bitters, oblix tonix', menuNum: '12' },
    { menuCol: 'rubus sparkler tanqueray london dry gin raspberry, lavender, lime, sparkling wine', menuNum: '123' },
    { menuCol: 'blueberry martini ketel one vodka, blueberry, violet, lemon, egg whites', menuNum: '123' },
    { menuCol: 'ginger peach mule bulleit bourbon, ginger peach cordial, lime, ginger beer', menuNum: '123' },
    { menuCol: 'watermelon spritzer aperol, watermelon, lemon, sparkling wine', menuNum: '123' },   { menuCol: 'ginger peach mule bulleit bourbon, ginger peach cordial, lime, ginger beer', menuNum: '123' },
    { menuCol: 'watermelon spritzer aperol, watermelon, lemon, sparkling wine', menuNum: '123' },   { menuCol: 'ginger peach mule bulleit bourbon, ginger peach cordial, lime, ginger beer', menuNum: '123' },
    { menuCol: 'watermelon spritzer aperol, waterme53345lon, lemon, sparkling wine', menuNum: '123' },   { menuCol: 'ginger peach mule bulleit bourbon, ginger peach cordial, lime, ginger beer', menuNum: '123' },
    { menuCol: 'watermelon spritzer aperol, watermelon, lemon, sparkling wine', menuNum: '123' },   { menuCol: 'ginger peach mule bulleit bourbon, ginger peach cordial, lime, ginger beer', menuNum: '123' },
    { menuCol: 'watermelon spritzer aperol, watermelon, lemon, sparkling wine', menuNum: '123' },   { menuCol: 'ginger peac534543h mule bulleit bourbon, ginger peach cordial, lime, ginger beer', menuNum: '123' },
    { menuCol: 'watermelon spritzer aperol, watermelon, lemon, sparkldrgdrging wine', menuNum: '123' },   { menuCol: 'ginger peach mule bulleit bourbon, ginger peach cordial, lime, ginger beer', menuNum: '123' },
    { menuCol: 'watermelon spritzer aperol, watermelon, lemon, sparkling wine', menuNum: '123' },
    {
      menuTitle: 'beers',
    },
    { menuCol: 'NOAM BAVAwRIAN LAGER (340ml)', menuNum: '12' },
    { menuCol: 'ST MUNGO LAGER (330ml)', menuNum: '123' },
    { menuCol: 'SASSY L’INIMITABLE APPLE', menuNum: '123' },
    { menuCol: 'CIDER (330ml)', menuNum: '123' },
    { menuCol: 'LUCKY SAINT ALCOeeeHOL FREE (330ml)', menuNum: '123' }],
  ],
  },
  
}